### ISSUE TITLE
include preliminary OISST

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/blueant#4]
I'd like to remove the *preliminary* rejection here: 

https://github.com/AustralianAntarcticDivision/blueant/blob/8dc3d0daf3b39665e0af78b38e38d38e81ebdef6/R/sources_sst.R#L12

I think that's ok, as long as our file listings prefer the validated forms eventually.

**Comment by raymondben** [comment]
No problem removing that `reject` clause: done. But, I don't know that it ever actually worked (at least not consistently), because the repo is full of preliminary files! Except for mid-October to about now. So I'm a little confused ... October was probably when I switched the VM from using the old raadsync package to bowerbird/blueant, maybe the rejection started working then. Anyway, the rejection is out now and prelim files seem to be getting downloaded again.
